const events=[
{id:'indo',date:'2026-10-02',name:'Indo Warehouse',subtitle:'Anyasa, Harji · South Asian electronic',kind:'music',genre:'Electronic / dance',venue:'Cermak Hall at Radius',city:'Chicago',time:'10:00 PM doors',ages:'18+ · valid government ID',address:'640 W Cermak Road, Chicago, IL',image:'https://images.discovery-prod.axs.com/2025/02/indo-warehouse_02-08-25_19_67a6bd6158b42.jpg',url:'https://www.axs.com/events/1488530/indo-warehouse-tickets',description:'A night of South Asian electronic music with Indo Warehouse, Anyasa, and Harji.',note:'Doors open at 10:00 PM. Check AXS for ticket prices and availability.'},
{id:'aura',date:'2026-10-09',name:'Sivaangi & Maanasi',subtitle:'Unlimited Aura · Tamil music, live',kind:'music',genre:'Tamil / live concert',venue:'Yellow Box',city:'Naperville',time:'7:00 PM doors',ages:'All ages',address:'1635 Emerson Lane, Naperville, IL',image:'https://usimg.sulekha.io/cdn/events/images/2026-09-21-09-25-00-758_63.webp',url:'https://events.sulekha.com/unlimited-aura-sivaangi-maanasi-live-chicago_event-in_naperville-il_401960',description:'Unlimited Aura brings Sivaangi and Maanasi to Naperville for an evening of Tamil music and live vocals.',note:'The organizer lists doors at 7:00 PM. Confirm the show start and duration with Sulekha.'},
{id:'kanan',date:'2026-10-11',name:'Kanan Gill',subtitle:'Not This Again · A brand-new stand-up show',kind:'comedy',genre:'Stand-up comedy',venue:'Park West',city:'Chicago',time:'7:00 PM',ages:'All ages',address:'Park West, Chicago, IL',image:'https://images.discovery-prod.axs.com/2026/01/uploadedimage_697d321b12809.jpg',url:'https://www.jamusa.com/events/detail/kanan-gill-1317677',description:'Kanan Gill returns with a new stand-up show, bringing his sharply observed humor to Park West.',note:'Doors open at 6:00 PM; the show starts at 7:00 PM. Tickets are linked from Jam Productions.'},
{id:'jaspreet',date:'2026-10-23',name:'Jaspreet Singh',subtitle:'Brand New Show · Stand-up in Hindi',kind:'comedy',genre:'Hindi / stand-up comedy',venue:'Ruth Page Blackbox Theater',city:'Chicago',time:'7:30 PM',ages:'16+ only',address:'1016 N Dearborn Street, Chicago, IL',image:'https://theticketworld.s3.us-east-2.amazonaws.com/Event/Jaspreet%20Chicago.png',url:'https://theticketworld.com/events/chicago-jaspreet-singh-live-2026-brand-new-show--tickets-10-23-2026-chicago-il-867',description:'Jaspreet Singh brings his new Hindi stand-up show to the Ruth Page Blackbox Theater.',note:'Doors at 6:30 PM. Approximate show length: 75 minutes. The organizer specifies a phone-free experience.'},
{id:'needful',date:'2026-10-31',name:'Do The Needful',subtitle:'Live on Halloween · Punk meets Bollywood',kind:'music',genre:'Punk Bollywood',venue:'Skylark',city:'Chicago',time:'8:30 PM',ages:'Confirm age policy with venue',address:'2149 S Halsted Street, Chicago, IL',url:'https://www.skylarkchicago.com/events/do-the-needful-live-oct-26',free:true,description:'Classic Bollywood anthems from the 1960s and 70s, reinterpreted through a punk lens. A Halloween night at Skylark.',note:'The venue lists no cover. Show starts at 8:30 PM. Confirm entry requirements directly with Skylark.'}
];
const $=s=>document.querySelector(s);const arrow='<svg class="arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12h17M13 5l7 7-7 7"/></svg>';const heart='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>';let saved=new Set();try{const v=JSON.parse(localStorage.getItem('desi-shortlist')||'[]');if(Array.isArray(v))saved=new Set(v.filter(id=>events.some(e=>e.id===id)))}catch{}let kind='all';let toastTimer;let restoreFocus;
const formatDate=(date,options)=>new Intl.DateTimeFormat('en-US',{...options,timeZone:'America/Chicago'}).format(new Date(`${date}T12:00:00-05:00`));
function saveButton(e){return `<button class="save" data-save="${e.id}" aria-label="${saved.has(e.id)?'Remove':'Save'} ${e.name} ${saved.has(e.id)?'from':'to'} shortlist" aria-pressed="${saved.has(e.id)}">${heart}</button>`}
function render(){const query=$('#search').value.trim().toLowerCase();const location=$('#location').value;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const rows=events.filter(e=>e.date>=today&&(kind==='all'||e.kind===kind)&&(location==='all'||(location==='suburbs'?e.city!=='Chicago':e.city===location))&&`${e.name} ${e.subtitle} ${e.venue} ${e.city} ${e.genre}`.toLowerCase().includes(query));$('#event-list').innerHTML=rows.map(e=>`<article class="event"><time class="date" datetime="${e.date}"><span>${formatDate(e.date,{month:'short'}).toUpperCase()}</span><strong>${Number(e.date.slice(-2))}</strong><small>${formatDate(e.date,{weekday:'short'}).toUpperCase()}</small></time>${e.image?`<img class="poster" src="${e.image}" alt="${e.name} event artwork" loading="lazy">`:`<div class="poster-fallback" aria-hidden="true">DTN</div>`}<div class="event-info"><div class="event-kicker">${e.kind} / ${e.genre}</div><h3><button class="event-title" data-detail="${e.id}">${e.name}</button></h3><p class="event-description">${e.subtitle}</p><p class="event-meta"><b>${e.venue}</b> · ${e.city}<br>${e.time}${e.free?' · No cover':''}</p></div><a class="tickets" href="${e.url}" target="_blank" rel="noopener noreferrer" aria-label="${e.free?'View venue details':'Get tickets'} for ${e.name} (opens in a new tab)"><span>${e.free?'Venue details':'Get tickets'}</span>${arrow}</a>${saveButton(e)}</article>`).join('');$('#empty').hidden=rows.length>0;$('#result-count').textContent=`${rows.length} upcoming ${rows.length===1?'night':'nights'} · October 2026`;$('#clear-filters').hidden=kind==='all'&&!query&&location==='all';document.querySelectorAll('.poster').forEach(img=>img.addEventListener('error',()=>{const div=document.createElement('div');div.className='poster-fallback';div.setAttribute('aria-hidden','true');div.textContent=img.alt.split(' ').slice(0,2).map(w=>w[0]).join('');img.replaceWith(div)}));updateCount()}
function updateCount(){$('#saved-count').textContent=saved.size}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function toggleSave(id){const e=events.find(e=>e.id===id);if(!e)return;const removing=saved.has(id);removing?saved.delete(id):saved.add(id);let persisted=true;try{localStorage.setItem('desi-shortlist',JSON.stringify([...saved]))}catch{persisted=false}document.querySelectorAll(`[data-save="${id}"]`).forEach(b=>{b.setAttribute('aria-pressed',saved.has(id));b.setAttribute('aria-label',`${saved.has(id)?'Remove':'Save'} ${e.name} ${saved.has(id)?'from':'to'} shortlist`)});updateCount();if($('#shortlist-dialog').open)renderShortlist();notify(`${e.name} ${removing?'removed from':'added to'} your shortlist.${persisted?'':' Storage unavailable; saved for this visit.'}`)}
function openDialog(id){restoreFocus=document.activeElement;$(id).showModal()}
function renderShortlist(){const rows=events.filter(e=>saved.has(e.id));$('#shortlist-list').innerHTML=rows.length?rows.map(e=>`<article class="short-event"><div><h3>${e.name}</h3><p>${formatDate(e.date,{month:'short',day:'numeric',year:'numeric'})} · ${e.time}<br>${e.venue} · ${e.city}</p><a href="${e.url}" target="_blank" rel="noopener noreferrer">${e.free?'Venue details':'Details & tickets'} ↗</a></div>${saveButton(e)}</article>`).join(''):'<div class="empty"><h3>Keep a night in mind.</h3><p>Tap a heart in the lineup to start your shortlist.</p><button class="text-link" data-close>Back to the lineup ↗</button></div>'}
function showDetail(id){const e=events.find(e=>e.id===id);if(!e)return;$('#detail-title').textContent=e.name;$('#detail-category').textContent=`${e.kind} / ${e.genre}`;$('#detail-content').innerHTML=`<p>${e.description}</p><dl class="detail-grid"><dt>When</dt><dd>${formatDate(e.date,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}<br>${e.time} · Chicago local time</dd><dt>Where</dt><dd>${e.venue}<br>${e.address}</dd><dt>Entry</dt><dd>${e.ages}${e.free?' · No cover':''}</dd></dl><p>${e.note}</p><div class="detail-actions"><a class="text-link" href="${e.url}" target="_blank" rel="noopener noreferrer">${e.free?'Open venue listing':'Details & tickets'} ${arrow}</a><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.address)}" target="_blank" rel="noopener noreferrer">Directions ↗</a></div><p>Organizer listing checked September 29, 2026. Prices and availability may change.</p>`;openDialog('#detail-dialog')}
function reset(){kind='all';$('#search').value='';$('#location').value='all';document.querySelectorAll('[data-kind]').forEach(b=>{b.classList.toggle('selected',b.dataset.kind==='all');b.setAttribute('aria-pressed',b.dataset.kind==='all')});render()}
document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save)toggleSave(save.dataset.save);const detail=e.target.closest('[data-detail]');if(detail)showDetail(detail.dataset.detail);const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close()});document.querySelectorAll('[data-kind]').forEach(button=>button.addEventListener('click',()=>{kind=button.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button)});render()}));$('#search').addEventListener('input',render);$('#location').addEventListener('change',render);$('#clear-filters').addEventListener('click',reset);$('#empty-reset').addEventListener('click',reset);$('#shortlist-open').addEventListener('click',()=>{renderShortlist();openDialog('#shortlist-dialog')});$('#about-open').addEventListener('click',()=>openDialog('#about-dialog'));document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>restoreFocus?.focus());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});render();

// Track public event IDs and selected categories only after analytics opt-in.
document.addEventListener('click', event => {
  const ticket = event.target.closest('.tickets, .short-event a, .detail-actions .text-link');
  if (ticket) {
    const listing = events.find(item => item.url === ticket.href);
    if (listing) window.siteAnalytics?.track('select_content', {content_type:'event', content_id:listing.id});
  }
  const filter = event.target.closest('[data-kind]');
  if (filter) window.siteAnalytics?.track('event_filter', {filter_name:filter.dataset.kind});
});
