const events=[
  {
    "id": "atul",
    "date": "2026-09-25",
    "name": "Atul Purohit",
    "subtitle": "Past performance",
    "kind": "music",
    "genre": "Past performance",
    "venue": "Wintrust Field",
    "city": "Schaumburg",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Wintrust Field, Schaumburg, IL",
    "url": "https://events.sulekha.com/atul-purohit-largest-outdoor-garba-in-chicago_event-in_schaumburg-il_400474",
    "description": "Atul Purohit performs at Wintrust Field in Schaumburg.",
    "note": "Historical listing preserved from the referenced chat; hidden from the upcoming lineup."
  },
  {
    "id": "falguni",
    "date": "2026-09-26",
    "name": "Falguni Pathak",
    "subtitle": "Past performance",
    "kind": "music",
    "genre": "Past performance",
    "venue": "Wintrust Field",
    "city": "Schaumburg",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Wintrust Field, Schaumburg, IL",
    "url": "https://events.sulekha.com/falguni-pathak-tour-falguni-pathak-dandiya-dhoom-2026-concert-tickets",
    "description": "Falguni Pathak performs at Wintrust Field in Schaumburg.",
    "note": "Historical listing preserved from the referenced chat; hidden from the upcoming lineup."
  },
  {
    "id": "soorya",
    "date": "2026-09-27",
    "name": "Sooryagayathri",
    "subtitle": "Past performance",
    "kind": "music",
    "genre": "Past performance",
    "venue": "Cutting Hall",
    "city": "Palatine",
    "time": "5:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Cutting Hall, Palatine, IL",
    "url": "https://www.sangeetcentral.com/concerts/sooryagayathri-2026-09-27",
    "description": "Sooryagayathri performs at Cutting Hall in Palatine.",
    "note": "Historical listing preserved from the referenced chat; hidden from the upcoming lineup."
  },
  {
    "id": "sunny",
    "date": "2026-09-27",
    "name": "Sunny Jadhav",
    "subtitle": "Past performance",
    "kind": "music",
    "genre": "Past performance",
    "venue": "Energy VBC",
    "city": "Bensenville",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Energy VBC, Bensenville, IL",
    "url": "https://events.sulekha.com/chicago-navratri-mahotsav_event-in_bensenville-il_401543",
    "description": "Sunny Jadhav performs at Energy VBC in Bensenville.",
    "note": "Historical listing preserved from the referenced chat; hidden from the upcoming lineup."
  },
  {
    "id": "saraswathi",
    "date": "2026-09-29",
    "name": "Saraswathi Ranganathan & Tzu-Tsen Wu",
    "subtitle": "Carnatic veena / world fusion",
    "kind": "music",
    "genre": "Carnatic veena / world fusion",
    "venue": "South Asia Institute",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "South Asia Institute, Chicago, IL",
    "url": "https://www.sangeetcentral.com/concerts/saraswathi-ranganathan-south-asia-institute-2026-09-29",
    "description": "Saraswathi Ranganathan & Tzu-Tsen Wu performs at South Asia Institute in Chicago.",
    "note": "World Music Festival Chicago. Doors at 6:00 PM; all ages.",
    "free": true,
    "image": "assets/events/saraswathi.webp",
    "imageSource": "https://qfixzbrkzofokewaokfi.supabase.co/storage/v1/object/public/artists/saraswathi-ranganathan.webp?v=1786762469"
  },
  {
    "id": "indo",
    "date": "2026-10-02",
    "name": "Indo Warehouse",
    "subtitle": "Anyasa, Harji · South Asian electronic",
    "kind": "music",
    "genre": "Electronic / dance",
    "venue": "Cermak Hall at Radius",
    "city": "Chicago",
    "time": "10:00 PM doors",
    "ages": "18+ · valid government ID",
    "address": "640 W Cermak Road, Chicago, IL",
    "image": "assets/events/indo.webp",
    "url": "https://www.axs.com/events/1488530/indo-warehouse-tickets",
    "description": "A night of South Asian electronic music with Indo Warehouse, Anyasa, and Harji.",
    "note": "Doors open at 10:00 PM. Check AXS for ticket prices and availability.",
    "imageSource": "https://images.discovery-prod.axs.com/2025/02/indo-warehouse_02-08-25_19_67a6bd6158b42.jpg"
  },
  {
    "id": "aghori",
    "date": "2026-10-02",
    "name": "Aghori Muzik",
    "subtitle": "Gujarati hip-hop / Garba",
    "kind": "music",
    "genre": "Gujarati hip-hop / Garba",
    "venue": "Canlan Sports Lake Barrington",
    "city": "Lake Barrington",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Canlan Sports Lake Barrington, Lake Barrington, IL",
    "url": "https://events.sulekha.com/aghori-muzik-hit-machine-of-gujarati-garba-night_event-in_barrington-il_401258",
    "description": "Aghori Muzik performs at Canlan Sports Lake Barrington in Lake Barrington.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/aghori.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/aghori-muzik-hit-machine-of-gujarati-garba-night_2026-08-08-11-08-23-640_7.webp"
  },
  {
    "id": "funkadesi",
    "date": "2026-10-03",
    "name": "Funkadesi",
    "subtitle": "Bhangra / Bollywood / funk",
    "kind": "music",
    "genre": "Bhangra / Bollywood / funk",
    "venue": "Gateway Park",
    "city": "Gary",
    "time": "4:45–6:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Gateway Park, Gary, IN",
    "url": "https://funkadesi.com/",
    "description": "Funkadesi performs at Gateway Park in Gary.",
    "note": "Healthy Community Festival. Free performance listed on the band’s official schedule.",
    "free": true,
    "image": "assets/events/funkadesi.webp",
    "imageSource": "https://funkadesi.com/wp-content/uploads/2021/11/Banner-TedX-Performance-480x327.jpg"
  },
  {
    "id": "arvind",
    "date": "2026-10-03",
    "name": "Arvind Vegda & Devanshi Shah",
    "subtitle": "Gujarati folk / Garba",
    "kind": "music",
    "genre": "Gujarati folk / Garba",
    "venue": "Jain Society of Metropolitan Chicago",
    "city": "Bartlett",
    "time": "6:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Jain Society of Metropolitan Chicago, Bartlett, IL",
    "url": "https://events.sulekha.com/arvind-vegda-and-devanshi-shah-live-in-chicago_event-in_bartlett-il_400543",
    "description": "Arvind Vegda & Devanshi Shah performs at Jain Society of Metropolitan Chicago in Bartlett.",
    "note": "Sulekha confirms cancellation and says the refund process has been initiated. Contact the provider for refund questions.",
    "status": "cancelled",
    "availabilityNote": "Cancelled · Sulekha says refunds have been initiated.",
    "linkLabel": "Event details",
    "verifiedOn": "2026-10-02",
    "image": "assets/events/arvind.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/arvind-vegda-and-devanshi-shah-live-in-chicago_2026-06-17-02-50-08-337_72.webp"
  },
  {
    "id": "kruthi",
    "date": "2026-10-03",
    "name": "Kruthi Bhat",
    "subtitle": "Carnatic vocal",
    "kind": "music",
    "genre": "Carnatic vocal",
    "venue": "Sri Venkateswara Swami (Balaji) Temple",
    "city": "Aurora",
    "time": "5:30 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Sri Venkateswara Swami (Balaji) Temple, Aurora, IL",
    "url": "https://chicagotyagarajautsavam.org/archives/14066",
    "description": "Kruthi Bhat performs at Sri Venkateswara Swami (Balaji) Temple in Aurora.",
    "note": "CTU and Balaji Temple present the Grand Carnatic Fall Concert. Check the linked event poster for the program and entry details.",
    "image": "assets/events/kruthi.webp",
    "imageSource": "https://chicagotyagarajautsavam.org/wp-content/uploads/2026/08/BalajiCTUCollabSruthi-800x1024.jpg"
  },
  {
    "id": "amit",
    "date": "2026-10-04",
    "name": "Amit Tandon",
    "subtitle": "HALWA · Stand-up comedy",
    "kind": "comedy",
    "genre": "HALWA · Stand-up comedy",
    "venue": "Hemmens Cultural Center",
    "city": "Elgin",
    "time": "6:30 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Hemmens Cultural Center, Elgin, IL",
    "url": "https://ohoproduction.com/",
    "description": "Amit Tandon performs at Hemmens Cultural Center in Elgin.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/amit.webp",
    "imageSource": "https://ohoproduction.com/Userdata/Event/Chicago-square_20260510055158994.jpg"
  },
  {
    "id": "geeta",
    "date": "2026-10-04",
    "name": "Geeta Rabari",
    "subtitle": "Gujarati folk / Garba",
    "kind": "music",
    "genre": "Gujarati folk / Garba",
    "venue": "Renaissance Schaumburg",
    "city": "Schaumburg",
    "time": "6:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Renaissance Schaumburg, Schaumburg, IL",
    "url": "https://events.sulekha.com/garba-ramzat-with-geeta-rabari-live-in-chicago_event-in_schaumburg-il_401522",
    "description": "Geeta Rabari performs at Renaissance Schaumburg in Schaumburg.",
    "note": "Online tickets are sold out on Sulekha. Tickets may still be available at the gates; contact organizer Manpasand to confirm before travelling.",
    "availabilityNote": "Online sold out · Gate tickets may be available; confirm with organizer.",
    "linkLabel": "Event details",
    "verifiedOn": "2026-10-02",
    "image": "assets/events/geeta.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/garba-ramzat-with-geeta-rabari-live-in-chicago_2026-08-23-03-27-08-922_81.webp"
  },
  {
    "id": "vatsala",
    "date": "2026-10-04",
    "name": "Vatsala Patil",
    "subtitle": "Gujarati / Hindi Garba",
    "kind": "music",
    "genre": "Gujarati / Hindi Garba",
    "venue": "Lorenas Banquet",
    "city": "Addison",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Lorenas Banquet, Addison, IL",
    "url": "https://events.sulekha.com/vatsala-patil-live-garba-2026-in-chicago_event-in_addison-il_401275",
    "description": "Vatsala Patil performs at Lorenas Banquet in Addison.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/vatsala.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/vatsala-patil-live-garba-2026-in-chicago_2026-08-10-11-17-49-123_73.webp"
  },
  {
    "id": "vik-10-05",
    "date": "2026-10-05",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "aura",
    "date": "2026-10-09",
    "name": "Sivaangi & Maanasi",
    "subtitle": "Unlimited Aura · Tamil music, live",
    "kind": "music",
    "genre": "Tamil / live concert",
    "venue": "Yellow Box",
    "city": "Naperville",
    "time": "7:00 PM doors",
    "ages": "All ages",
    "address": "1635 Emerson Lane, Naperville, IL",
    "image": "assets/events/aura.webp",
    "url": "https://events.sulekha.com/unlimited-aura-sivaangi-maanasi-live-chicago_event-in_naperville-il_401960",
    "description": "Unlimited Aura brings Sivaangi and Maanasi to Naperville for an evening of Tamil music and live vocals.",
    "note": "The organizer lists doors at 7:00 PM. This Sulekha page provides event information; a ticket purchase path has not been verified. Confirm show start, duration, and ticket availability with the organizer.",
    "availabilityNote": "Event information · Ticket purchase path not verified.",
    "linkLabel": "Event details",
    "verifiedOn": "2026-10-02",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/unlimited-aura-sivaangi-maanasi-live-chicago_2026-09-21-09-05-02-508_55.webp"
  },
  {
    "id": "jahnavi",
    "date": "2026-10-09",
    "name": "Jahnavi Harrison",
    "subtitle": "Kirtan / devotional music",
    "kind": "music",
    "genre": "Kirtan / devotional music",
    "venue": "SPACE",
    "city": "Evanston",
    "time": "Previously 8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "SPACE, Evanston, IL",
    "url": "https://songkick.com/concerts/43201287-jahnavi-harrison-at-space",
    "description": "Jahnavi Harrison performs at SPACE in Evanston.",
    "note": "Appears cancelled: Songkick marks it cancelled, while older ticket pages still show the event. Hidden from upcoming shows pending venue confirmation.",
    "status": "unconfirmed"
  },
  {
    "id": "beach",
    "date": "2026-10-10",
    "name": "DJ Miss Bhalla, DJ Capslock & DJ Ujwal",
    "subtitle": "Bollywood / Bhangra / Indo-house",
    "kind": "music",
    "genre": "Bollywood / Bhangra / Indo-house",
    "venue": "Whispers at Oak Street Beach",
    "city": "Chicago",
    "time": "1:00–9:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Whispers at Oak Street Beach, Chicago, IL",
    "url": "https://events.sulekha.com/bollywood-on-the-beach-oct-10th-oak-st-beach_event-in_chicago-il_402001",
    "description": "DJ Miss Bhalla, DJ Capslock & DJ Ujwal performs at Whispers at Oak Street Beach in Chicago.",
    "note": "21+. Capslock 1–5 PM; Miss Bhalla 5–7 PM; Ujwal 7–9 PM. Check the organizer for weather or schedule changes.",
    "image": "assets/events/dj-miss-bhalla.webp",
    "imageSource": "https://ugc.production.linktr.ee/PAwPsqsKQNe1Zmt0uKSM_IMG_8322.JPG",
    "imageSourcePage": "https://linktr.ee/djmissbhalla",
    "imageAlt": "DJ Miss Bhalla performing at the DJ decks"
  },
  {
    "id": "mehul",
    "date": "2026-10-10",
    "name": "Mehul Rami & Friends / Suravali Garba Group",
    "subtitle": "Garba & Dandiya · HMLC",
    "kind": "music",
    "genre": "Garba & Dandiya · HMLC",
    "venue": "Canlan Sports",
    "city": "Libertyville",
    "time": "7:00 PM–midnight",
    "ages": "Confirm age policy with organizer",
    "address": "Canlan Sports, Libertyville, IL",
    "url": "https://events.sulekha.com/garba-dandiya-with-mehul-rami-friends-in-association-with-hmlc_event-in_libertyville-il_401353",
    "description": "Mehul Rami & Friends / Suravali Garba Group performs at Canlan Sports in Libertyville.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/mehul.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/garba-dandiya-with-mehul-rami-friends-in-association-with-hmlc_2026-08-16-11-11-14-931_19.webp"
  },
  {
    "id": "kanan",
    "date": "2026-10-11",
    "name": "Kanan Gill",
    "subtitle": "Not This Again · A brand-new stand-up show",
    "kind": "comedy",
    "genre": "Stand-up comedy",
    "venue": "Park West",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "All ages",
    "address": "Park West, Chicago, IL",
    "image": "assets/events/kanan.webp",
    "url": "https://www.jamusa.com/events/detail/kanan-gill-1317677",
    "description": "Kanan Gill returns with a new stand-up show, bringing his sharply observed humor to Park West.",
    "note": "Doors open at 6:00 PM; the show starts at 7:00 PM. Tickets are linked from Jam Productions.",
    "imageSource": "https://images.discovery-prod.axs.com/2026/01/uploadedimage_697d321b12809.jpg"
  },
  {
    "id": "vik-10-12",
    "date": "2026-10-12",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "dhruv",
    "date": "2026-10-13",
    "name": "dhruv",
    "subtitle": "Pop / R&B · Opening for Jessie Ware",
    "kind": "music",
    "genre": "Pop / R&B · Opening for Jessie Ware",
    "venue": "Aragon Ballroom",
    "city": "Chicago",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Aragon Ballroom, Chicago, IL",
    "url": "https://www.livenation.com/event/vv1A7ZkoyGkdaJQVG/jessie-ware-the-superbloom-tour",
    "description": "dhruv performs at Aragon Ballroom in Chicago.",
    "note": "Jessie Ware’s Superbloom Tour; dhruv is the supporting artist. Doors at 7:00 PM.",
    "image": "assets/events/dhruv.webp",
    "imageSource": "https://s1.ticketm.net/dam/a/954/54d13bc4-8136-4bbc-910a-f82751b17954_TABLET_LANDSCAPE_LARGE_16_9.jpg"
  },
  {
    "id": "fakira",
    "date": "2026-10-16",
    "name": "Fakira",
    "subtitle": "Bengali folk / fusion · Durga Puja",
    "kind": "music",
    "genre": "Bengali folk / fusion · Durga Puja",
    "venue": "Midwest Conference Center",
    "city": "Melrose Park",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Midwest Conference Center, Melrose Park, IL",
    "url": "https://events.sulekha.com/fakira-music-live-on-durga-puja-chicago_event-in_melrose-park-il_401582",
    "description": "Fakira performs at Midwest Conference Center in Melrose Park.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/fakira.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/fakira-music-live-on-durga-puja-chicago_2026-08-27-02-51-35-931_8.webp"
  },
  {
    "id": "ravi",
    "date": "2026-10-16",
    "name": "Ravi Gupta",
    "subtitle": "Kal Ki Chinta Nahi Karta · Stand-up",
    "kind": "comedy",
    "genre": "Kal Ki Chinta Nahi Karta · Stand-up",
    "venue": "Athenaeum Center — Historic Main Stage",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Athenaeum Center — Historic Main Stage, Chicago, IL",
    "url": "https://www.eventticketscenter.com/ravi-gupta-chicago-tickets/1482361/e",
    "description": "Ravi Gupta performs at Athenaeum Center — Historic Main Stage in Chicago.",
    "note": "Listed by a secondary ticket marketplace. A first-party venue/promoter listing has not been verified; confirm with Athenaeum before purchasing.",
    "image": "assets/events/ravi-gupta.webp",
    "imageSource": "https://ugc.production.linktr.ee/iInmgEwfS2yQc7Uhk7KJ_LZbhSs9X7TW066Zw",
    "imageSourcePage": "https://linktr.ee/raviguptacomedy",
    "imageAlt": "Ravi Gupta holding a microphone"
  },
  {
    "id": "gurleen",
    "date": "2026-10-17",
    "name": "Gurleen Pannu",
    "subtitle": "Monster · Stand-up comedy",
    "kind": "comedy",
    "genre": "Monster · Stand-up comedy",
    "venue": "Pfeiffer Hall, North Central College",
    "city": "Naperville",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Pfeiffer Hall, North Central College, Naperville, IL",
    "url": "https://ohoproduction.com/",
    "description": "Gurleen Pannu performs at Pfeiffer Hall, North Central College in Naperville.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/gurleen.webp",
    "imageSource": "https://ohoproduction.com/Userdata/Event/Chicago-square%20(1)_20260721071908990.jpg"
  },
  {
    "id": "dipan",
    "date": "2026-10-17",
    "name": "Dipan Mitra & Shalini Mukherjee",
    "subtitle": "Hindi / Bengali vocals · Durga Puja",
    "kind": "music",
    "genre": "Hindi / Bengali vocals · Durga Puja",
    "venue": "Midwest Conference Center",
    "city": "Melrose Park",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Midwest Conference Center, Melrose Park, IL",
    "url": "https://events.sulekha.com/dipan-shalini-musical-live-performance-on-durga-puja-in-chicago_event-in_melrose-park-il_401590",
    "description": "Dipan Mitra & Shalini Mukherjee performs at Midwest Conference Center in Melrose Park.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/dipan.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/dipan-shalini-musical-live-performance-on-durga-puja-in-chicago_2026-08-27-06-09-46-087_63.webp"
  },
  {
    "id": "needful-oak",
    "date": "2026-10-18",
    "name": "Do The Needful",
    "subtitle": "Side Yard Sounds · Punk Bollywood",
    "kind": "music",
    "genre": "Side Yard Sounds · Punk Bollywood",
    "venue": "Compound Yellow",
    "city": "Oak Park",
    "time": "5:00–7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Compound Yellow, Oak Park, IL",
    "url": "https://events.ticketleap.com/tickets/compound-yellow/side-yard-sounds-do-the-needful-870699395",
    "description": "Do The Needful performs at Compound Yellow in Oak Park.",
    "note": "Tracked from the official Compound Yellow listing in the referenced chat. Ticketleap could not be retrieved during this comparison; confirm directly with the organizer.",
    "image": "assets/events/needful-oak.webp",
    "imageSource": "https://tlt-events.s3.amazonaws.com/5786/2200055/1f50094c62a01a90ee1d8389a094a96b76f550990ba4bf9ce481af3ca63eaf5b/e9029c6f-2a3c-4338-bf2e-105d71318776.png"
  },
  {
    "id": "indradeep",
    "date": "2026-10-18",
    "name": "Indradeep Ghosh",
    "subtitle": "Hindustani classical violin",
    "kind": "music",
    "genre": "Hindustani classical violin",
    "venue": "United Church of Rogers Park",
    "city": "Chicago",
    "time": "6:30 PM",
    "ages": "Confirm age policy with organizer",
    "address": "United Church of Rogers Park, Chicago, IL",
    "url": "https://www.ochinpakhichicago.org/event/gaanmela-pop-up-event-indradeep-ghosh/",
    "description": "Indradeep Ghosh performs at United Church of Rogers Park in Chicago.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "free": true,
    "image": "assets/events/indradeep.webp",
    "imageSource": "https://www.ochinpakhichicago.org/wp-content/uploads/2026/04/LuciaIndroYusuf-1024x576.jpeg"
  },
  {
    "id": "richa",
    "date": "2026-10-18",
    "name": "Richa Sharma",
    "subtitle": "Bollywood / Hindi & Bengali · Durga Puja",
    "kind": "music",
    "genre": "Bollywood / Hindi & Bengali · Durga Puja",
    "venue": "Midwest Conference Center",
    "city": "Northlake",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Midwest Conference Center, Northlake, IL",
    "url": "https://events.sulekha.com/richa-sharma-live-musical-concert-on-durga-puja-in-chicago_event-in_northlake-il_401594",
    "description": "Richa Sharma performs at Midwest Conference Center in Northlake.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/richa.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/richa-sharma-live-musical-concert-on-durga-puja-in-chicago_2026-08-27-07-17-25-566_15.webp"
  },
  {
    "id": "vik-10-19",
    "date": "2026-10-19",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "jaspreet",
    "date": "2026-10-23",
    "name": "Jaspreet Singh",
    "subtitle": "Brand New Show · Stand-up in Hindi",
    "kind": "comedy",
    "genre": "Hindi / stand-up comedy",
    "venue": "Ruth Page Blackbox Theater",
    "city": "Chicago",
    "time": "7:30 PM",
    "ages": "16+ only",
    "address": "1016 N Dearborn Street, Chicago, IL",
    "image": "assets/events/jaspreet.webp",
    "url": "https://theticketworld.com/events/chicago-jaspreet-singh-live-2026-brand-new-show--tickets-10-23-2026-chicago-il-867",
    "description": "Jaspreet Singh brings his new Hindi stand-up show to the Ruth Page Blackbox Theater.",
    "note": "Doors at 6:30 PM. Approximate show length: 75 minutes. The organizer specifies a phone-free experience.",
    "imageSource": "https://theticketworld.s3.us-east-2.amazonaws.com/Event/Jaspreet%20Chicago.png"
  },
  {
    "id": "ochin-library",
    "date": "2026-10-25",
    "name": "Ochin Pakhi",
    "subtitle": "Bengali folk music",
    "kind": "music",
    "genre": "Bengali folk music",
    "venue": "Vernon Area Public Library",
    "city": "Lincolnshire",
    "time": "1:00–2:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Vernon Area Public Library, Lincolnshire, IL",
    "url": "https://calendar.vapld.info/event/okhim-pakhi-folk-band-performance-101997",
    "description": "Ochin Pakhi performs at Vernon Area Public Library in Lincolnshire.",
    "note": "Free admission; registration required through the library.",
    "free": true,
    "image": "assets/events/ochin-library.webp",
    "imageSource": "https://www.ochinpakhichicago.org/wp-content/uploads/2026/04/Group_OP_8MB-768x512.jpg"
  },
  {
    "id": "vik-10-26",
    "date": "2026-10-26",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "needful",
    "date": "2026-10-31",
    "name": "Do The Needful",
    "subtitle": "Live on Halloween · Punk meets Bollywood",
    "kind": "music",
    "genre": "Punk Bollywood",
    "venue": "Skylark",
    "city": "Chicago",
    "time": "8:30 PM",
    "ages": "Confirm age policy with venue",
    "address": "2149 S Halsted Street, Chicago, IL",
    "url": "https://www.skylarkchicago.com/events/do-the-needful-live-oct-26",
    "free": true,
    "description": "Classic Bollywood anthems from the 1960s and 70s, reinterpreted through a punk lens. A Halloween night at Skylark.",
    "note": "The venue lists no cover. Show starts at 8:30 PM. Confirm entry requirements directly with Skylark.",
    "image": "assets/events/needful.webp",
    "imageSource": "https://static1.squarespace.com/static/67351cb55165643349394ddb/673b9a3519547e4f6a917356/6a64db16518f516bb6ce24c7/1784995407706/DTN_Halloween_26.jpg?format=1500w"
  },
  {
    "id": "sagar",
    "date": "2026-10-31",
    "name": "Sagar Bhatia",
    "subtitle": "Sagar Wali Qawwali",
    "kind": "music",
    "genre": "Sagar Wali Qawwali",
    "venue": "Renaissance Schaumburg",
    "city": "Schaumburg",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Renaissance Schaumburg, Schaumburg, IL",
    "url": "https://events.sulekha.com/sagar-wali-qawwali-sagar-bhatia-live-concert-2026-in-chicago_event-in_schaumburg-il_401790",
    "description": "Sagar Bhatia performs at Renaissance Schaumburg in Schaumburg.",
    "note": "This active Renaissance listing replaces the earlier cancelled/postponed National India Hub listing. Use this venue and ticket link.",
    "image": "assets/events/sagar.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/sagar-wali-qawwali-sagar-bhatia-live-concert-2026-in-chicago_2026-09-10-02-39-15-215_63.webp"
  },
  {
    "id": "kinjal",
    "date": "2026-10-31",
    "name": "Kinjal Dave",
    "subtitle": "Killol · Gujarati Garba",
    "kind": "music",
    "genre": "Killol · Gujarati Garba",
    "venue": "Renaissance Schaumburg",
    "city": "Schaumburg",
    "time": "6:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Renaissance Schaumburg, Schaumburg, IL",
    "url": "https://events.sulekha.com/killol-in-chicago-with-kinjal-dave_event-in_schaumburg-il_401521",
    "description": "Kinjal Dave performs at Renaissance Schaumburg in Schaumburg.",
    "note": "Provider confirms cancellation and says refunds have been initiated.",
    "status": "cancelled"
  },
  {
    "id": "ochin-lalon",
    "date": "2026-11-01",
    "name": "Ochin Pakhi",
    "subtitle": "Songs of Lalon Fakir · Bengali / Baul folk",
    "kind": "music",
    "genre": "Songs of Lalon Fakir · Bengali / Baul folk",
    "venue": "Kalapriya Studio",
    "city": "Chicago",
    "time": "4:00–6:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Kalapriya Studio, Chicago, IL",
    "url": "https://kalapriya.org/events/songsoflalonfakir",
    "description": "Ochin Pakhi performs at Kalapriya Studio in Chicago.",
    "note": "Concert followed by discussion and Q&A. Kalapriya Studio: 2101 S Wabash Avenue.",
    "image": "assets/events/ochin-lalon.webp",
    "imageSource": "https://static1.squarespace.com/static/60870449aa98ed1f34b390c8/t/6a8f407da06e1c1c9fd2c9ec/1787773053449/Facebook+Event+Landscape+%281%29.jpg?format=1500w"
  },
  {
    "id": "anup",
    "date": "2026-11-01",
    "name": "Anup Jalota",
    "subtitle": "Sangeet Sandhya · Bollywood / bhajan",
    "kind": "music",
    "genre": "Sangeet Sandhya · Bollywood / bhajan",
    "venue": "Haridham Chicago",
    "city": "Schaumburg",
    "time": "5:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Haridham Chicago, Schaumburg, IL",
    "url": "https://events.sulekha.com/anup-jalota-live-in-concert-chicago-sangeet-sandhya-2026_event-in_schaumburg-il_401953",
    "description": "Anup Jalota performs at Haridham Chicago in Schaumburg.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/anup.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/anup-jalota-live-in-concert-chicago-sangeet-sandhya-2026_2026-09-20-11-47-50-963_91.webp"
  },
  {
    "id": "vik-11-02",
    "date": "2026-11-02",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "shaarib",
    "date": "2026-11-06",
    "name": "Shaarib & Toshi",
    "subtitle": "Bollywood / Sufi",
    "kind": "music",
    "genre": "Bollywood / Sufi",
    "venue": "Fair Play at Compass Arena",
    "city": "Willowbrook",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Fair Play at Compass Arena, Willowbrook, IL",
    "url": "https://events.sulekha.com/qawali-night-with-arsalan-rabbani-in-il_event-in_willowbrook-il_400349",
    "description": "Shaarib & Toshi performs at Fair Play at Compass Arena in Willowbrook.",
    "note": "Current listing body and city calendar show November 6; the provider’s URL/page title retains older event text. Confirm with the organizer before booking.",
    "image": "assets/events/shaarib.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/shaarib-toshi-live-concert_2026-06-02-06-46-55-971_39.webp"
  },
  {
    "id": "ochin-gaanmela",
    "date": "2026-11-06",
    "name": "Ochin Pakhi",
    "subtitle": "GaanMela · Bengali folk",
    "kind": "music",
    "genre": "GaanMela · Bengali folk",
    "venue": "United Church of Rogers Park",
    "city": "Chicago",
    "time": "9:45 PM",
    "ages": "Confirm age policy with organizer",
    "address": "United Church of Rogers Park, Chicago, IL",
    "url": "https://www.ochinpakhichicago.org/gaanmela/",
    "description": "Ochin Pakhi performs at United Church of Rogers Park in Chicago.",
    "note": "Free GaanMela festival performance in the Sanctuary, 1545 W Morse Avenue.",
    "free": true,
    "image": "assets/events/ochin-library.webp",
    "imageSource": "https://www.ochinpakhichicago.org/wp-content/uploads/2026/04/Group_OP_8MB-768x512.jpg"
  },
  {
    "id": "shounak",
    "date": "2026-11-08",
    "name": "Shounak Abhisheki",
    "subtitle": "Diwali Morning Concert · Indian classical",
    "kind": "music",
    "genre": "Diwali Morning Concert · Indian classical",
    "venue": "Al Larson Prairie Center for the Arts",
    "city": "Schaumburg",
    "time": "9:30 AM",
    "ages": "Confirm age policy with organizer",
    "address": "Al Larson Prairie Center for the Arts, Schaumburg, IL",
    "url": "https://events.sulekha.com/diwali-morning-concert-in-chicago-il_event-in_schaumburg-il_400388",
    "description": "Shounak Abhisheki performs at Al Larson Prairie Center for the Arts in Schaumburg.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/shounak.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/diwali-morning-concert-in-chicago-il_2026-06-04-04-48-37-799_14.webp"
  },
  {
    "id": "vik-11-09",
    "date": "2026-11-09",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "ashish",
    "date": "2026-11-13",
    "name": "Ashish Kulkarni & Avnie Singh",
    "subtitle": "Diwali Celebration · Bollywood",
    "kind": "music",
    "genre": "Diwali Celebration · Bollywood",
    "venue": "Haridham Temple",
    "city": "Schaumburg",
    "time": "7:15 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Haridham Temple, Schaumburg, IL",
    "url": "https://events.sulekha.com/diwali-celebration-with-ashish-kulkarni-avnie-singh-in-chicago_event-in_schaumburg-il_401585",
    "description": "Ashish Kulkarni & Avnie Singh performs at Haridham Temple in Schaumburg.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/ashish.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/diwali-celebration-with-ashish-kulkarni-avnie-singh-in-illinois_2026-08-27-03-23-47-189_61.webp"
  },
  {
    "id": "vik-11-16",
    "date": "2026-11-16",
    "name": "Vik Pandya",
    "subtitle": "Late Nite Mic · Hosted comedy",
    "kind": "comedy",
    "genre": "Late Nite Mic · Hosted comedy",
    "venue": "The Comedy Bar",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "The Comedy Bar, Chicago, IL",
    "url": "https://www.eventbrite.com/cc/mondays-late-nite-mic-w-vik-pandya-513829/",
    "description": "Vik Pandya performs at The Comedy Bar in Chicago.",
    "note": "17+. Dates and time were tracked in the referenced chat; the Eventbrite collection could not be retrieved during this comparison. Confirm this specific Monday before booking.",
    "image": "assets/events/vik-10-05.webp",
    "imageSource": "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F963795893%2F264096330549%2F1%2Foriginal.20250218-223151?auto=format%2Ccompress&q=75&sharp=10&s=02b5a16b682f6c7e490dfa876449275c"
  },
  {
    "id": "prateek",
    "date": "2026-11-17",
    "name": "Prateek Kuhad",
    "subtitle": "Full Moon Chamber Tour · Acoustic",
    "kind": "music",
    "genre": "Full Moon Chamber Tour · Acoustic",
    "venue": "Park West",
    "city": "Chicago",
    "time": "7:30 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Park West, Chicago, IL",
    "url": "https://www.jamusa.com/venue/park-west/",
    "description": "Prateek Kuhad performs at Park West in Chicago.",
    "note": "Official Park West calendar marks this performance cancelled.",
    "status": "cancelled"
  },
  {
    "id": "rohan",
    "date": "2026-11-19",
    "name": "Rohan Joshi",
    "subtitle": "Getting There · Stand-up comedy",
    "kind": "comedy",
    "genre": "Getting There · Stand-up comedy",
    "venue": "Chicago Improv",
    "city": "Schaumburg",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Chicago Improv, Schaumburg, IL",
    "url": "https://improv.com/chicago/calendar/nov-2026/",
    "description": "Rohan Joshi performs at Chicago Improv in Schaumburg.",
    "note": "21+. Doors at 5:00 PM; two-item minimum. Buy through the official Improv website.",
    "image": "assets/events/rohan.webp",
    "imageSource": "https://i.ticketweb.com/i/00/13/44/27/43_Listings.jpg?v=2"
  },
  {
    "id": "udit",
    "date": "2026-11-20",
    "name": "Udit Narayan & Aditya Narayan",
    "subtitle": "Legacy · Bollywood",
    "kind": "music",
    "genre": "Legacy · Bollywood",
    "venue": "Aura Club and Conventions",
    "city": "Naperville",
    "time": "8:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Aura Club and Conventions, Naperville, IL",
    "url": "https://events.sulekha.com/legacy-udit-narayan-aditya-narayan-in-il_event-in_naperville-il_401792",
    "description": "Udit Narayan & Aditya Narayan performs at Aura Club and Conventions in Naperville.",
    "note": "Confirm current entry requirements, prices, and availability with the linked provider.",
    "image": "assets/events/udit.webp",
    "imageSource": "https://usimg.sulekha.io/cdn/events/images/thumbnail/legacy-%E2%80%93-udit-narayan-aditya-narayan-in-il_2026-09-10-12-15-48-286_80.webp"
  },
  {
    "id": "pranit",
    "date": "2026-11-21",
    "name": "Pranit More",
    "subtitle": "Ghayal · Hindi stand-up",
    "kind": "comedy",
    "genre": "Ghayal · Hindi stand-up",
    "venue": "Yellow Box",
    "city": "Naperville",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "Yellow Box, Naperville, IL",
    "url": "https://linktr.ee/millennialeventscorp",
    "description": "Pranit More performs at Yellow Box in Naperville.",
    "note": "Millennial Events North American tour. Doors at 6:00 PM; follow the organizer’s Chicago tour link for tickets.",
    "image": "assets/events/pranit.webp",
    "imageSource": "https://ugc.production.linktr.ee/d673ef01-00e2-4107-99f1-5ccbf33cab64_thumb6aa788ad42145.jpeg?io=true&size=thumbnail-stack_v1_0"
  },
  {
    "id": "mohini-early",
    "date": "2026-11-24",
    "name": "Mohini Dey",
    "subtitle": "Jazz / fusion · Bass & vocals",
    "kind": "music",
    "genre": "Jazz / fusion · Bass & vocals",
    "venue": "City Winery Chicago",
    "city": "Chicago",
    "time": "6:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "City Winery Chicago, Chicago, IL",
    "url": "https://tickets.citywinery.com/event/mohini-dey-h806eq",
    "description": "Mohini Dey performs at City Winery Chicago in Chicago.",
    "note": "Separate ticket required for each performance. City Winery: 1200 W Randolph Street.",
    "image": "assets/events/mohini-early.webp",
    "imageSource": "https://s3.eu-central-1.amazonaws.com/yt-s3/b988cd53-f47c-4786-8929-70e4acaa2944.jpg"
  },
  {
    "id": "mohini-late",
    "date": "2026-11-24",
    "name": "Mohini Dey",
    "subtitle": "Jazz / fusion · Bass & vocals",
    "kind": "music",
    "genre": "Jazz / fusion · Bass & vocals",
    "venue": "City Winery Chicago",
    "city": "Chicago",
    "time": "9:30 PM",
    "ages": "Confirm age policy with organizer",
    "address": "City Winery Chicago, Chicago, IL",
    "url": "https://tickets.citywinery.com/event/mohini-dey-j48neh",
    "description": "Mohini Dey performs at City Winery Chicago in Chicago.",
    "note": "Separate ticket required for each performance. City Winery: 1200 W Randolph Street.",
    "image": "assets/events/mohini-early.webp",
    "imageSource": "https://s3.eu-central-1.amazonaws.com/yt-s3/b988cd53-f47c-4786-8929-70e4acaa2944.jpg"
  },
  {
    "id": "butter-chicken-red-line",
    "date": "2026-10-16",
    "name": "Butter Chicken Brass Band & Mandala Arts",
    "subtitle": "Red Line Jazz Festival · South Asian brass / jazz",
    "kind": "music",
    "genre": "South Asian brass / jazz",
    "venue": "Harris Theater",
    "city": "Chicago",
    "time": "7:30 PM",
    "ages": "Confirm age policy with venue",
    "address": "205 E Randolph Street, Chicago, IL 60601",
    "url": "https://www.harristheaterchicago.org/performance/red-line-jazz-festival",
    "description": "Butter Chicken Brass Band joins Mandala Arts’ Red Line Jazz Festival, curated by Fareed Haque.",
    "note": "Official venue and organizer confirm the date and ticket link. Approximate runtime: two hours including intermission.",
    "image": "assets/events/red-line-jazz.webp",
    "imageSource": "https://www.harristheaterchicago.org/sites/default/files/styles/2000x1200/public/2026-06/RDLJ26_2000x1200_event%20image.jpg.webp?h=f1946b31&itok=1eYDKhuH",
    "verifiedOn": "2026-09-29"
  },
  {
    "date": "2026-11-07",
    "kind": "music",
    "venue": "United Church of Rogers Park",
    "city": "Chicago",
    "ages": "Confirm age policy with organizer",
    "address": "1545 W Morse Avenue, Chicago, IL 60626",
    "url": "https://www.ochinpakhichicago.org/gaanmela/",
    "free": true,
    "verifiedOn": "2026-09-29",
    "id": "arun-qais-gaanmela",
    "name": "Arun Sabapathy & Qais Worroryar",
    "subtitle": "GaanMela · Tabla & Afghan rubab",
    "genre": "Tabla / rubab",
    "time": "2:30 PM",
    "description": "Tabla player Arun Sabapathy accompanies Qais Worroryar on rubab.",
    "note": "Free GaanMela performance on the Upstairs stage; the organizer confirms this set time.",
    "image": "assets/events/arun-sabapathy.webp",
    "imageSource": "https://www.ochinpakhichicago.org/wp-content/uploads/2026/09/ArunSabapathy.jpeg"
  },
  {
    "date": "2026-11-07",
    "kind": "music",
    "venue": "United Church of Rogers Park",
    "city": "Chicago",
    "ages": "Confirm age policy with organizer",
    "address": "1545 W Morse Avenue, Chicago, IL 60626",
    "url": "https://www.ochinpakhichicago.org/gaanmela/",
    "free": true,
    "verifiedOn": "2026-09-29",
    "id": "aikyam-gaanmela",
    "name": "Tanveer Singh Sapra & Aikyam live ensemble",
    "subtitle": "GaanMela · Vocals, bansuri, violin & Arun Sabapathy on tabla",
    "genre": "Hindustani music / Odissi",
    "time": "6:30 PM",
    "description": "Tanveer Singh Sapra, Sonny Patel, Lucia Thomas and Arun Sabapathy provide live music for Aikyam Odissi Dance Collective.",
    "note": "Free GaanMela performance in the Sanctuary; the organizer confirms this set time.",
    "image": "assets/events/aikyam.webp",
    "imageSource": "https://www.ochinpakhichicago.org/wp-content/uploads/2026/09/colinmascarenhas-943x1024.jpeg"
  },
  {
    "date": "2026-11-07",
    "kind": "music",
    "venue": "United Church of Rogers Park",
    "city": "Chicago",
    "ages": "Confirm age policy with organizer",
    "address": "1545 W Morse Avenue, Chicago, IL 60626",
    "url": "https://www.ochinpakhichicago.org/gaanmela/",
    "free": true,
    "verifiedOn": "2026-09-29",
    "id": "arun-lehra-gaanmela",
    "name": "Arun Sabapathy with Lehra Lehra",
    "subtitle": "GaanMela · Sindhi folk / Sufi with tabla",
    "genre": "Sindhi folk / Sufi",
    "time": "8:45 PM",
    "description": "Arun Sabapathy joins Lehra Lehra’s Sindhi folk and Sufi ensemble on tabla.",
    "note": "Free GaanMela performance on the Upstairs stage; the organizer confirms this set time.",
    "image": "assets/events/lehra-lehra.webp",
    "imageSource": "https://www.ochinpakhichicago.org/wp-content/uploads/2026/09/LehraLehra-e1788542340594-1024x693.png"
  },
  {
    "id": "nimesh-joliet",
    "date": "2026-11-14",
    "name": "Nimesh Patel",
    "subtitle": "Stand-up comedy",
    "kind": "comedy",
    "genre": "Stand-up comedy",
    "venue": "Hollywood Casino Joliet",
    "city": "Joliet",
    "time": "8:00 PM",
    "ages": "Confirm event-specific age policy with venue",
    "address": "1401 Gateway Boulevard, Joliet, IL 60431",
    "url": "https://www.ticketmaster.com/nimesh-patel-joliet-illinois-11-14-2026/event/070064FDA476329A",
    "description": "Indian-American comedian and writer Nimesh Patel performs at Hollywood Casino Joliet.",
    "note": "Official Ticketmaster event and venue listings confirm November 14 at 8:00 PM. Confirm entry requirements and current ticket availability with the provider.",
    "verifiedOn": "2026-09-29",
    "image": "assets/events/nimesh-patel.webp",
    "imageSource": "https://s1.ticketm.net/dam/a/581/c62603f9-c6ff-41bb-8794-fb0338525581_RETINA_PORTRAIT_3_2.jpg",
    "imageSourcePage": "https://www.ticketmaster.com/nimesh-patel-joliet-illinois-11-14-2026/event/070064FDA476329A",
    "imageAlt": "Nimesh Patel promotional photograph"
  },
  {
    "id": "pallavi-chicago",
    "date": "2026-11-06",
    "name": "Pallavi Mahidhara",
    "subtitle": "Rembrandt Chamber Musicians · Piano & strings",
    "kind": "music",
    "genre": "Classical piano / chamber music",
    "venue": "Chicago Temple, Dixon Chapel",
    "city": "Chicago",
    "time": "7:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "77 W Washington Street, 2nd Floor, Chicago, IL 60602",
    "url": "https://www.rembrandtchambermusicians.org/full-list-of-events",
    "description": "Indian-American pianist Pallavi Mahidhara joins Rembrandt Chamber Musicians for works by Beethoven, Frank Bridge, and Dohnányi.",
    "note": "Pallavi Mahidhara plays Dohnanyi. Date, local time, and venue confirmed by the official Rembrandt season calendar. Check the provider for ticket availability and entry policies.",
    "verifiedOn": "2026-09-30",
    "image": "assets/events/pallavi-rembrandt.webp",
    "imageSource": "https://www.musicinst.org/sites/default/files/images/RembrandtChamber2026-2027.png",
    "imageSourcePage": "https://www.musicinst.org/events/rembrandt-chamber-musicians-presents-pallavi-mahidhara-plays-dohnanyi",
    "imageAlt": "Official poster for Pallavi Mahidhara with Rembrandt Chamber Musicians, November 6 in Chicago and November 8 in Evanston."
  },
  {
    "id": "pallavi-evanston",
    "date": "2026-11-08",
    "name": "Pallavi Mahidhara",
    "subtitle": "Rembrandt Chamber Musicians · Piano & strings",
    "kind": "music",
    "genre": "Classical piano / chamber music",
    "venue": "Nichols Concert Hall",
    "city": "Evanston",
    "time": "3:00 PM",
    "ages": "Confirm age policy with organizer",
    "address": "1490 Chicago Avenue, Evanston, IL 60201",
    "url": "https://www.musicinst.org/events/rembrandt-chamber-musicians-presents-pallavi-mahidhara-plays-dohnanyi",
    "description": "Indian-American pianist Pallavi Mahidhara joins Rembrandt Chamber Musicians for works by Beethoven, Frank Bridge, and Dohnányi.",
    "note": "Pallavi Mahidhara plays Dohnanyi. Date, local time, and venue confirmed by the official Rembrandt season calendar. Check the provider for ticket availability and entry policies.",
    "verifiedOn": "2026-09-30",
    "image": "assets/events/pallavi-rembrandt.webp",
    "imageSource": "https://www.musicinst.org/sites/default/files/images/RembrandtChamber2026-2027.png",
    "imageSourcePage": "https://www.musicinst.org/events/rembrandt-chamber-musicians-presents-pallavi-mahidhara-plays-dohnanyi",
    "imageAlt": "Official poster for Pallavi Mahidhara with Rembrandt Chamber Musicians, November 6 in Chicago and November 8 in Evanston."
  }

].sort((a,b)=>a.date.localeCompare(b.date));
const externalArrow='<svg class="external-arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12"/></svg>';const $=s=>document.querySelector(s);const arrow='<svg class="arrow" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12h17M13 5l7 7-7 7"/></svg>';const heart='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>';let saved=new Set();try{const v=JSON.parse(localStorage.getItem('desi-shortlist')||'[]');if(Array.isArray(v))saved=new Set(v.filter(id=>events.some(e=>e.id===id)))}catch{}let kind='all';let toastTimer;let restoreFocus;
const formatDate=(date,options)=>new Intl.DateTimeFormat('en-US',{...options,timeZone:'America/Chicago'}).format(new Date(`${date}T12:00:00-05:00`));
function saveButton(e){return `<button class="save" data-save="${e.id}" aria-label="${saved.has(e.id)?'Remove':'Save'} ${e.name} ${saved.has(e.id)?'from':'to'} shortlist" aria-pressed="${saved.has(e.id)}">${heart}</button>`}
function render(){const query=$('#search').value.trim().toLowerCase();const location=$('#location').value;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const rows=events.filter(e=>!e.status&&e.date>=today&&(kind==='all'||e.kind===kind||(kind==='free'&&e.free===true))&&(location==='all'||(location==='suburbs'?e.city!=='Chicago':e.city===location))&&`${e.name} ${e.subtitle} ${e.venue} ${e.city} ${e.genre}`.toLowerCase().includes(query));$('#event-list').innerHTML=rows.map(e=>`<article class="event" data-event="${e.id}"><time class="date" datetime="${e.date}"><span>${formatDate(e.date,{month:'short'}).toUpperCase()}</span><strong>${Number(e.date.slice(-2))}</strong><small>${formatDate(e.date,{weekday:'short'}).toUpperCase()}</small></time>${e.image?`<img class="poster" src="${e.image}" alt="${e.imageAlt||`${e.name} event artwork`}" loading="lazy">`:`<div class="poster-fallback" aria-hidden="true">${e.name.split(' ').slice(0,2).map(w=>w[0]).join('')}</div>`}<div class="event-info"><div class="event-kicker">${e.kind} / ${e.genre}</div><h3><button class="event-title" data-detail="${e.id}">${e.name}</button></h3><p class="event-description">${e.subtitle}</p><p class="event-meta"><b>${e.venue}</b> · ${e.city}<br>${e.time}${e.free?' · Free admission':''}${e.availabilityNote?`<br>${e.availabilityNote}`:''}</p></div><a class="tickets" data-event-link="${e.id}" href="${e.url}" target="_blank" rel="noopener noreferrer" aria-label="${e.linkLabel||(e.free?'View venue details':'Get tickets')} for ${e.name} (opens in a new tab)"><span>${e.linkLabel||(e.free?'Venue details':'Get tickets')}</span>${arrow}</a>${saveButton(e)}</article>`).join('');$('#empty').hidden=rows.length>0;$('#result-count').textContent=`${rows.length} upcoming ${rows.length===1?'night':'nights'} · Fall 2026`;$('#clear-filters').hidden=kind==='all'&&!query&&location==='all';document.querySelectorAll('.poster').forEach(img=>img.addEventListener('error',()=>{const div=document.createElement('div');div.className='poster-fallback';div.setAttribute('aria-hidden','true');div.textContent=img.alt.split(' ').slice(0,2).map(w=>w[0]).join('');img.replaceWith(div)}));updateCount()}
function updateCount(){$('#saved-count').textContent=saved.size}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
function toggleSave(id){const e=events.find(e=>e.id===id);if(!e)return;const removing=saved.has(id);removing?saved.delete(id):saved.add(id);let persisted=true;try{localStorage.setItem('desi-shortlist',JSON.stringify([...saved]))}catch{persisted=false}document.querySelectorAll(`[data-save="${id}"]`).forEach(b=>{b.setAttribute('aria-pressed',saved.has(id));b.setAttribute('aria-label',`${saved.has(id)?'Remove':'Save'} ${e.name} ${saved.has(id)?'from':'to'} shortlist`)});updateCount();if($('#shortlist-dialog').open)renderShortlist();notify(`${e.name} ${removing?'removed from':'added to'} your shortlist.${persisted?'':' Storage unavailable; saved for this visit.'}`)}
function openDialog(id){restoreFocus=document.activeElement;$(id).showModal()}
function renderShortlist(){const rows=events.filter(e=>saved.has(e.id));$('#shortlist-list').innerHTML=rows.length?rows.map(e=>`<article class="short-event"><div><h3>${e.name}</h3><p>${formatDate(e.date,{month:'short',day:'numeric',year:'numeric'})} · ${e.time}<br>${e.venue} · ${e.city}${e.availabilityNote?`<br>${e.availabilityNote}`:''}</p><a data-event-link="${e.id}" href="${e.url}" target="_blank" rel="noopener noreferrer">${e.linkLabel||(e.free?'Venue details':'Details & tickets')} ${externalArrow}</a></div>${saveButton(e)}</article>`).join(''):'<div class="empty"><h3>Keep a night in mind.</h3><p>Tap a heart in the lineup to start your shortlist.</p><button class="text-link" data-close>Back to the lineup ${externalArrow}</button></div>'}
function showDetail(id){const e=events.find(e=>e.id===id);if(!e)return;$('#detail-title').textContent=e.name;$('#detail-category').textContent=`${e.kind} / ${e.genre}`;$('#detail-content').innerHTML=`<p>${e.description}</p><dl class="detail-grid"><dt>When</dt><dd>${formatDate(e.date,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}<br>${e.time} · Chicago local time</dd><dt>Where</dt><dd>${e.venue}<br>${e.address}</dd><dt>Entry</dt><dd>${e.ages}${e.free?' · Free admission':''}</dd></dl><p>${e.note}</p><div class="detail-actions"><a class="text-link" data-event-link="${e.id}" href="${e.url}" target="_blank" rel="noopener noreferrer">${e.linkLabel||(e.free?'Open venue listing':'Details & tickets')} ${arrow}</a><a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(e.address)}" target="_blank" rel="noopener noreferrer">Directions ${externalArrow}</a></div><p>${e.verifiedOn?`Checked against the official listing on ${formatDate(e.verifiedOn,{month:'long',day:'numeric',year:'numeric'})}.`:'Compared with tracked listings September 29, 2026. Source limitations are noted above.'} Prices and availability may change.</p>`;openDialog('#detail-dialog')}
function reset(){kind='all';$('#search').value='';$('#location').value='all';document.querySelectorAll('[data-kind]').forEach(b=>{b.classList.toggle('selected',b.dataset.kind==='all');b.setAttribute('aria-pressed',b.dataset.kind==='all')});render()}
document.addEventListener('click',e=>{const save=e.target.closest('[data-save]');if(save)toggleSave(save.dataset.save);const detail=e.target.closest('[data-detail]');const row=e.target.closest('[data-event]');if(detail)showDetail(detail.dataset.detail);else if(row&&!e.target.closest('a,button'))showDetail(row.dataset.event);const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close()});document.querySelectorAll('[data-kind]').forEach(button=>button.addEventListener('click',()=>{kind=button.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button)});render()}));$('#search').addEventListener('input',render);$('#location').addEventListener('change',render);$('#clear-filters').addEventListener('click',reset);$('#empty-reset').addEventListener('click',reset);$('#shortlist-open').addEventListener('click',()=>{renderShortlist();openDialog('#shortlist-dialog')});$('#about-open').addEventListener('click',()=>openDialog('#about-dialog'));document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>restoreFocus?.focus());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});render();

// Track public event IDs and categories only when the analytics policy permits collection.
document.addEventListener('click', event => {
  const link = event.target.closest('a[data-event-link]');
  if (link) {
    const listing = events.find(item => item.id === link.dataset.eventLink);
    if (listing) window.siteAnalytics?.track('select_content', {
      content_type: 'event',
      content_id: listing.id,
      link_type: listing.free ? 'venue_details' : 'tickets'
    });
  }
  const filter = event.target.closest('[data-kind]');
  if (filter) window.siteAnalytics?.track('event_filter', {filter_name:filter.dataset.kind});
});


// Native controls stay available on desktop; mobile can expand them on demand.
const searchToggle = $('#search-toggle');
searchToggle.addEventListener('click', () => {
  const expanded = searchToggle.getAttribute('aria-expanded') !== 'true';
  searchToggle.setAttribute('aria-expanded', String(expanded));
  searchToggle.closest('.search-tools').classList.toggle('is-open', expanded);
  searchToggle.querySelector('span').textContent = expanded ? '−' : '+';
});

// Move only the desktop artwork, and stop work once the hero leaves the viewport.
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)');
const desktopHero = matchMedia('(min-width: 761px)');
const hero = $('.hero');
const heroImage = $('.hero-art img');
let heroVisible = true;
let heroFrame = 0;
function updateHeroParallax() {
  heroFrame = 0;
  const enabled = desktopHero.matches && !reducedMotion.matches;
  const offset = enabled ? Math.min(36, Math.max(0, -hero.getBoundingClientRect().top * .08)) : 0;
  heroImage.style.setProperty('--hero-offset', `${offset}px`);
}
function scheduleHeroParallax() {
  if (!heroFrame) heroFrame = requestAnimationFrame(updateHeroParallax);
}
window.addEventListener('scroll', () => {
  if (heroVisible && desktopHero.matches && !reducedMotion.matches) scheduleHeroParallax();
}, {passive: true});
window.addEventListener('resize', scheduleHeroParallax);
reducedMotion.addEventListener('change', scheduleHeroParallax);
desktopHero.addEventListener('change', scheduleHeroParallax);
if ('IntersectionObserver' in window) {
  new IntersectionObserver(([entry]) => {
    heroVisible = entry.isIntersecting;
    if (heroVisible) scheduleHeroParallax();
  }).observe(hero);
}
scheduleHeroParallax();

// A brief pulse for deliberate mobile actions, where vibration is supported.
function mobileHaptic(event) {
  if (!event.isTrusted || reducedMotion.matches || !matchMedia('(pointer: coarse)').matches || typeof navigator.vibrate !== 'function') return;
  const control = event.target.closest('button, .tickets, .short-event a, .detail-actions a, .search-toggle, .event[data-event], .listing-updates summary');
  if (!control || control.disabled) return;
  try { navigator.vibrate(10); } catch { /* Feedback must never interrupt an action. */ }
}
document.addEventListener('click', mobileHaptic, {capture: true});
$('#location').addEventListener('change', mobileHaptic);
